wam:
  # Schunk Powerball joints
  j1_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  j2_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  j3_controller:
    type: effort_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  j4_controller:
    type: effort_controllers/JointPositionController
    joint: arm_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  j5_controller:
    type: effort_controllers/JointPositionController
    joint: arm_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  j6_controller:
    type: effort_controllers/JointPositionController
    joint: arm_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}    
  j7_controller:
    type: effort_controllers/JointPositionController
    joint: arm_7_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}    
   
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

